# Generated by Django 5.2.5 on 2025-12-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decirlo', 'Prefiero no decirlo')], max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(help_text='PIN de 4 dígitos para acceso rápido', max_length=4)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('condiciones_medicas', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('psicologo_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('compartir_datos_medicos', models.BooleanField(default=False)),
                ('recibir_recordatorios', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pwms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil PWMS',
                'verbose_name_plural': 'Perfiles PWMS',
            },
        ),
        migrations.CreateModel(
            name='RegistroFisiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('frecuencia_cardiaca', models.IntegerField(help_text='Latidos por minuto')),
                ('presion_arterial_sistolica', models.IntegerField(help_text='Presión sistólica (alta)')),
                ('presion_arterial_diastolica', models.IntegerField(help_text='Presión diastólica (baja)')),
                ('temperatura', models.DecimalField(decimal_places=1, help_text='Temperatura en °C', max_digits=4)),
                ('oxigenacion_sangre', models.IntegerField(help_text='SpO2 en porcentaje')),
                ('pasos_diarios', models.IntegerField(default=0)),
                ('calorias_quemadas', models.IntegerField(default=0)),
                ('horas_sueno', models.DecimalField(decimal_places=1, help_text='Horas de sueño', max_digits=4)),
                ('dispositivo_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_fisiologicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Fisiológico',
                'verbose_name_plural': 'Registros Fisiológicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel_estres', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='1=Sin estrés, 10=Máximo estrés')),
                ('nivel_ansiedad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='1=Sin ansiedad, 10=Máxima ansiedad')),
                ('estado_animo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='1=Muy bajo, 10=Muy alto')),
                ('notas_dia', models.TextField(help_text='¿Cómo te sientes hoy?')),
                ('eventos_significativos', models.TextField(blank=True, help_text='Eventos importantes del día', null=True)),
                ('pensamientos_recurrentes', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_psicologicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Psicológico',
                'verbose_name_plural': 'Registros Psicológicos',
                'ordering': ['-fecha'],
            },
        ),
    ]
