# Generated by Django 5.2.5 on 2026-04-29 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWMS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='VideoAnalisisEstrés',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_estres_facial', models.FloatField(default=0.0, help_text='0-100')),
                ('emocion_dominante', models.CharField(blank=True, max_length=50)),
                ('micro_sonrisa', models.FloatField(default=0.0)),
                ('micro_ceño', models.FloatField(default=0.0)),
                ('micro_parpadeo', models.FloatField(default=0.0)),
                ('micro_labios', models.FloatField(default=0.0)),
                ('micro_frente', models.FloatField(default=0.0)),
                ('variabilidad_emocional', models.FloatField(default=0.0)),
                ('tiempo_relajado', models.FloatField(default=0.0)),
                ('tiempo_tension', models.FloatField(default=0.0)),
                ('datos_raw', models.JSONField(blank=True, null=True)),
                ('evaluacion_nasa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PWMS.evaluacionnasatlx')),
                ('evaluacion_zung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PWMS.zunganxietyscale')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Estrés Facial',
                'verbose_name_plural': 'Análisis de Estrés Facial',
            },
        ),
    ]
