# Generated by Django 5.2.5 on 2025-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofisiologico',
            name='nivel_estres',
            field=models.IntegerField(blank=True, help_text='Nivel de estrés (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='registrofisiologico',
            name='notas_adicionales',
            field=models.TextField(blank=True, help_text='Notas adicionales del usuario', null=True),
        ),
        migrations.AddField(
            model_name='registrofisiologico',
            name='puntuacion_sueno',
            field=models.IntegerField(blank=True, help_text='Puntuación de sueño (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='registrofisiologico',
            name='dispositivo_origen',
            field=models.CharField(blank=True, default='HealthSync Pro', max_length=50, null=True),
        ),
    ]
