# Generated by Django 5.2.5 on 2026-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWMS', '0002_registrofisiologico_nivel_estres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofisiologico',
            name='estres_alto',
            field=models.IntegerField(default=0, help_text='Porcentaje de tiempo con estrés alto (0-100%)'),
        ),
        migrations.AddField(
            model_name='registrofisiologico',
            name='estres_bajo',
            field=models.IntegerField(default=0, help_text='Porcentaje de tiempo con estrés bajo (0-100%)'),
        ),
        migrations.AddField(
            model_name='registrofisiologico',
            name='estres_moderado',
            field=models.IntegerField(default=0, help_text='Porcentaje de tiempo con estrés moderado (0-100%)'),
        ),
        migrations.AddField(
            model_name='registrofisiologico',
            name='estres_relajado',
            field=models.IntegerField(default=0, help_text='Porcentaje de tiempo relajado (0-100%)'),
        ),
        migrations.AlterField(
            model_name='registrofisiologico',
            name='nivel_estres',
            field=models.IntegerField(blank=True, help_text='Nivel de estrés calculado (0-100)', null=True),
        ),
    ]
