# Generated by Django 5.2.5 on 2026-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWMS', '0002_mission_description_videoanalisisestrés'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropsicologico',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='registropsicologico',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='sesiongrabacionnasatlx',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='sesiongrabacionnasatlx',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='videoanalisisestrés',
            name='evaluacion_nasa',
        ),
        migrations.RemoveField(
            model_name='videoanalisisestrés',
            name='evaluacion_zung',
        ),
        migrations.RemoveField(
            model_name='videoanalisisestrés',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p01_me_siento_mas_nervioso',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='1. Me siento más nervioso y ansioso que de costumbre'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p02_siento_miedo_sin_razon',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='2. Siento miedo sin razón'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p03_me_siento_alterado',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='3. Me siento alterado o agitado'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p04_siento_que_me_desmorono',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='4. Siento que me estoy desmoronando'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p05_siento_que_todo_bien',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='5. Siento que todo está bien y no pasará nada malo'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p06_temblor_sacudidas',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='6. Tiemblan mis manos, brazos o piernas'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p07_dolores_cabeza_cuello',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='7. Tengo dolores de cabeza, cuello o espalda'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p08_debilidad_fatiga',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='8. Me siento débil y me canso fácilmente'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p09_siento_calma_tranquilidad',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='9. Me siento calmado y puedo permanecer en calma fácilmente'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p10_siento_latidos_corazon',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='10. Siento latidos del corazón rápidos'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p11_mareos',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='11. Tengo mareos o vértigo'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p12_desmayos',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='12. Siento que me voy a desmayar'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p13_respiracion_normal',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='13. Puedo respirar normal'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p14_entumecimiento_hormigueo',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='14. Tengo entumecimiento u hormigueo en dedos, manos o pies'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p15_dolores_estomacales',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='15. Tengo dolores de estómago o indigestión'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p16_necesidad_orinar',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='16. Tengo necesidad frecuente de orinar'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p17_manos_calidas_secas',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='17. Mis manos están normalmente calientes y secas'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p18_sonrojo_bochorno',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='18. Mi cara se sonroja y siento bochornos'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p19_duermo_bien_descanso',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='19. Duermo bien y descanso'),
        ),
        migrations.AlterField(
            model_name='zunganxietyscale',
            name='p20_pesadillas',
            field=models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='20. Tengo pesadillas'),
        ),
        migrations.DeleteModel(
            name='FrameNASATLX',
        ),
        migrations.DeleteModel(
            name='RegistroPsicologico',
        ),
        migrations.DeleteModel(
            name='SesionGrabacionNASATLX',
        ),
        migrations.DeleteModel(
            name='VideoAnalisisEstrés',
        ),
    ]
