# Generated by Django 5.2.5 on 2026-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWMS', '0003_registrofisiologico_estres_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofisiologico',
            name='horas_sueno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas de sueño (ej: 7.75 = 7 horas 45 minutos) ', max_digits=5, null=True),
        ),
    ]
