# Generated by Django 5.2.5 on 2026-03-24 17:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWMS', '0004_alter_registrofisiologico_horas_sueno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpwms',
            name='baseline_cognitive',
            field=models.FloatField(blank=True, help_text='Baseline cognitive (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='perfilpwms',
            name='baseline_fatigue',
            field=models.FloatField(blank=True, help_text='Baseline fatigue (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='perfilpwms',
            name='baseline_stress',
            field=models.FloatField(blank=True, help_text='Baseline stress (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='perfilpwms',
            name='experience',
            field=models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Experienced', 'Experienced'), ('Veteran', 'Veteran')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilpwms',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='perfilpwms',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='perfilpwms',
            name='role',
            field=models.CharField(blank=True, choices=[('Commander', 'Commander'), ('Pilot', 'Pilot'), ('Scientist', 'Scientist'), ('Engineer', 'Engineer'), ('MedicalOfficer', 'Medical Officer'), ('PayloadSpecialist', 'Payload Specialist')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registropsicologico',
            name='fatiga',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Fatiga 1-10', null=True),
        ),
        migrations.AddField(
            model_name='registropsicologico',
            name='negative_affect',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Afecto negativo 1-10', null=True),
        ),
        migrations.AddField(
            model_name='registropsicologico',
            name='positive_affect',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Afecto positivo 1-10', null=True),
        ),
        migrations.AlterField(
            model_name='registrofisiologico',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='EvaluacionNASATLX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('tarea_descripcion', models.TextField(blank=True, help_text='Describa la tarea específica que realizó', verbose_name='Descripción de la tarea evaluada')),
                ('demanda_mental', models.IntegerField(default=50, help_text='¿Cuánta actividad mental requirió la tarea? (0=Mínima, 100=Máxima)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Demanda Mental')),
                ('demanda_fisica', models.IntegerField(default=50, help_text='¿Cuánta actividad física requirió la tarea? (0=Mínima, 100=Máxima)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Demanda Física')),
                ('demanda_temporal', models.IntegerField(default=50, help_text='¿Qué presión de tiempo sentiste? (0=Ninguna, 100=Máxima)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Demanda Temporal')),
                ('rendimiento', models.IntegerField(default=50, help_text='¿Cómo valoras tu éxito en la tarea? (0=Muy insatisfecho, 100=Muy satisfecho)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rendimiento')),
                ('esfuerzo', models.IntegerField(default=50, help_text='¿Cuánto esfuerzo invertiste? (0=Mínimo, 100=Máximo)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Esfuerzo')),
                ('frustracion', models.IntegerField(default=50, help_text='¿Cuánta frustración sentiste? (0=Ninguna, 100=Máxima)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Frustración')),
                ('peso_demanda_mental', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Peso Demanda Mental')),
                ('peso_demanda_fisica', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Peso Demanda Física')),
                ('peso_demanda_temporal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Peso Demanda Temporal')),
                ('peso_rendimiento', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Peso Rendimiento')),
                ('peso_esfuerzo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Peso Esfuerzo')),
                ('peso_frustracion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Peso Frustración')),
                ('puntuacion_total', models.FloatField(default=0.0, help_text='Puntuación ponderada de carga mental (0-100)', verbose_name='Puntuación TLX Total')),
                ('notas_adicionales', models.TextField(blank=True, help_text='Observaciones adicionales sobre la evaluación', verbose_name='Notas Adicionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evaluación NASA TLX',
                'verbose_name_plural': 'Evaluaciones NASA TLX',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la misión')),
                ('habitat_type', models.CharField(max_length=50, verbose_name='Tipo de hábitat')),
                ('duration_days', models.IntegerField(verbose_name='Duración en días')),
                ('phases', models.JSONField(default=list, verbose_name='Fases (lista de dicts con name, start, end)')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('crew_members', models.ManyToManyField(related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='Tripulantes')),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
            },
        ),
        migrations.CreateModel(
            name='SesionGrabacionNASATLX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='videos_nasa_tlx/%Y/%m/%d/', verbose_name='Video de la sesión')),
                ('nombre_video', models.CharField(blank=True, max_length=255, verbose_name='Nombre del archivo de video')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de grabación')),
                ('duracion_segundos', models.IntegerField(default=120, help_text='Duración total de la grabación en segundos', verbose_name='Duración (segundos)')),
                ('total_frames', models.IntegerField(default=0, help_text='Número total de frames capturados', verbose_name='Total de frames')),
                ('intervalo_captura', models.IntegerField(default=10, help_text='Intervalo en segundos entre cada frame', verbose_name='Intervalo de captura (segundos)')),
                ('completada', models.BooleanField(default=False, verbose_name='Grabación completada')),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_grabacion', to='PWMS.evaluacionnasatlx', verbose_name='Evaluación NASA TLX')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_grabacion_tlx', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Grabación NASA TLX',
                'verbose_name_plural': 'Sesiones de Grabación NASA TLX',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='ZungAnxietyScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('p01_me_siento_mas_nervioso', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Me siento más nervioso y ansioso que de costumbre')),
                ('p02_siento_miedo_sin_razon', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Siento miedo sin razón')),
                ('p03_me_siento_alterado', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Me siento alterado o agitado')),
                ('p04_siento_que_me_desmorono', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Siento que me estoy desmoronando')),
                ('p05_siento_que_todo_bien', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Siento que todo está bien y no pasará nada malo')),
                ('p06_temblor_sacudidas', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tiemblan mis manos, brazos o piernas')),
                ('p07_dolores_cabeza_cuello', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tengo dolores de cabeza, cuello o espalda')),
                ('p08_debilidad_fatiga', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Me siento débil y me canso fácilmente')),
                ('p09_siento_calma_tranquilidad', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Me siento calmado y puedo permanecer en calma fácilmente')),
                ('p10_siento_latidos_corazon', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Siento latidos del corazón rápidos')),
                ('p11_mareos', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tengo mareos o vértigo')),
                ('p12_desmayos', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Siento que me voy a desmayar')),
                ('p13_respiracion_normal', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Puedo respirar normal')),
                ('p14_entumecimiento_hormigueo', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tengo entumecimiento u hormigueo en dedos, manos o pies')),
                ('p15_dolores_estomacales', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tengo dolores de estómago o indigestión')),
                ('p16_necesidad_orinar', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tengo necesidad frecuente de orinar')),
                ('p17_manos_calidas_secas', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Mis manos están normalmente calientes y secas')),
                ('p18_sonrojo_bochorno', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Mi cara se sonroja y siento bochornos')),
                ('p19_duermo_bien_descanso', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Duermo bien y descanso')),
                ('p20_pesadillas', models.IntegerField(choices=[(1, 'Rara vez'), (2, 'Algunas veces'), (3, 'Buena parte del tiempo'), (4, 'La mayor parte del tiempo')], verbose_name='Tengo pesadillas')),
                ('puntuacion_bruta', models.IntegerField(blank=True, help_text='Suma total de las respuestas', null=True, verbose_name='Puntuación bruta')),
                ('puntuacion_indice', models.IntegerField(blank=True, help_text='Puntuación bruta × 1.25 (escala de 25-100)', null=True, verbose_name='Índice de Ansiedad')),
                ('nivel_ansiedad', models.CharField(blank=True, choices=[('normal', 'Dentro de lo normal (25-44)'), ('minima', 'Ansiedad mínima a moderada (45-59)'), ('marcada', 'Ansiedad marcada a severa (60-74)'), ('extrema', 'Ansiedad extrema (75-100)')], max_length=20, null=True, verbose_name='Nivel de ansiedad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('video_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del video')),
                ('video_metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos del video (resolución, fps, etc.)')),
                ('video_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño del video (bytes)')),
                ('video_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración del video (segundos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_ansiedad_zung', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Escala de Ansiedad de Zung',
                'verbose_name_plural': 'Escalas de Ansiedad de Zung',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='FrameNASATLX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='frames_nasa_tlx/%Y/%m/%d/', verbose_name='Frame')),
                ('timestamp_segundos', models.FloatField(help_text='Momento exacto de captura en segundos desde inicio', verbose_name='Timestamp (segundos)')),
                ('numero_frame', models.IntegerField(verbose_name='Número de frame')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='PWMS.sesiongrabacionnasatlx', verbose_name='Sesión de grabación')),
            ],
            options={
                'verbose_name': 'Frame NASA TLX',
                'verbose_name_plural': 'Frames NASA TLX',
                'ordering': ['numero_frame'],
                'unique_together': {('sesion', 'numero_frame')},
            },
        ),
    ]
