# Generated by Django 5.2.1 on 2025-11-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('agua', 'Agua'), ('energia', 'Energia'), ('oxigeno', 'Oxigeno'), ('alimentos', 'Alimentos')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'agua'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
    ]
