# Generated by Django 5.2.1 on 2026-01-30 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('energia', 'Energia'), ('agua', 'Agua'), ('oxigeno', 'Oxigeno'), ('co2', 'CO2'), ('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('alimentos', 'Alimentos'), ('temperatura_alimentos', 'Temperatura_Alimentos')], max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'agua'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porciones_iniciales', models.PositiveIntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)])),
                ('porciones_actuales', models.PositiveIntegerField(default=112, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_tripulantes', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('porciones_por_persona_dia', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('duracion_mision_dias', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('comida', 'Comida'), ('cena', 'Cena')], max_length=20)),
                ('personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('porciones', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso_alimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='HABUI_APP.recursoalimentos')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.FloatField(help_text='Concentración de CO₂ en ppm')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'co2'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.FloatField()),
                ('corriente', models.FloatField()),
                ('potencia', models.FloatField()),
                ('factor_potencia', models.FloatField(blank=True, null=True)),
                ('frecuencia', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'energia'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Humedad relativa (%)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'humedad'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoOxigeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(help_text='Concentración de O₂ en %')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'oxigeno'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en °C')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'temperatura'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en °C')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'temperatura_alimentos'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
    ]
