# Generated by Django 5.2.1 on 2025-11-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HABUI_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursoagua',
            name='ph',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('energia', 'Energia'), ('agua', 'Agua'), ('oxigeno', 'Oxigeno'), ('co2', 'CO2'), ('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('alimentos', 'Alimentos')], max_length=20),
        ),
    ]
