# Generated by Django 5.2.1 on 2026-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HABUI_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=50)),
                ('escenario', models.CharField(max_length=10)),
                ('sample_id', models.CharField(max_length=120, unique=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('estado_esperado', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_clasificado', models.CharField(blank=True, max_length=30, null=True)),
                ('clasificacion_correcta', models.BooleanField(default=False)),
                ('alerta_esperada', models.BooleanField(default=False)),
                ('alerta_activada', models.BooleanField(default=False)),
                ('alerta_correcta', models.BooleanField(default=False)),
                ('tstart', models.DateTimeField()),
                ('tgen', models.DateTimeField(blank=True, null=True)),
                ('tsync', models.DateTimeField(blank=True, null=True)),
                ('lp_ms', models.FloatField(blank=True, null=True)),
                ('lcr_ms', models.FloatField(blank=True, null=True)),
                ('trs_ms', models.FloatField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
