# Generated by Django 5.2.1 on 2025-12-09 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HABUI_APP', '0002_remove_recursoagua_ph_alter_recurso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('energia', 'Energia'), ('agua', 'Agua'), ('oxigeno', 'Oxigeno'), ('co2', 'CO2'), ('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('alimentos', 'Alimentos'), ('temperatura_alimentos', 'Temperatura_Alimentos')], max_length=35),
        ),
        migrations.CreateModel(
            name='RecursoAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porciones_iniciales', models.PositiveIntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)])),
                ('porciones_actuales', models.PositiveIntegerField(default=112, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_tripulantes', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('porciones_por_persona_dia', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('duracion_mision_dias', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('comida', 'Comida'), ('cena', 'Cena')], max_length=20)),
                ('personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('porciones', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso_alimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='HABUI_APP.recursoalimentos')),
            ],
        ),
    ]
