# Generated by Django 5.2.1 on 2026-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HABUI_APP', '0002_metricamonitoreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoenergia',
            name='autonomia_h',
            field=models.FloatField(blank=True, help_text='Autonomía estimada restante en horas', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='balance_acumulado_wh',
            field=models.FloatField(blank=True, help_text='Balance energético acumulado en Wh', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='balance_w',
            field=models.FloatField(blank=True, help_text='Diferencia instantánea entre generación solar y consumo en W', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='capacidad_bateria_wh',
            field=models.FloatField(blank=True, help_text='Capacidad total del banco de baterías en Wh', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='energia_bateria_wh',
            field=models.FloatField(blank=True, help_text='Energía restante en el banco de baterías en Wh', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='energia_consumida_wh',
            field=models.FloatField(blank=True, help_text='Energía acumulada consumida por el hábitat en Wh', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='energia_generada_wh',
            field=models.FloatField(blank=True, help_text='Energía solar acumulada generada en Wh', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='estado_energia',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='modo_baja_energia',
            field=models.BooleanField(default=False, help_text='Indica si el sistema activó el protocolo de baja energía'),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='potencia_consumida_w',
            field=models.FloatField(blank=True, help_text='Potencia instantánea consumida por el hábitat en W', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='potencia_generada_w',
            field=models.FloatField(blank=True, help_text='Potencia instantánea generada por los paneles solares en W', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='soc_bateria_pct',
            field=models.FloatField(blank=True, help_text='Estado de carga de la batería en porcentaje', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='temperatura_bateria_c',
            field=models.FloatField(blank=True, help_text='Temperatura estimada o medida del banco de baterías en °C', null=True),
        ),
        migrations.AddField(
            model_name='recursoenergia',
            name='temperatura_panel_c',
            field=models.FloatField(blank=True, help_text='Temperatura estimada o medida del panel solar en °C', null=True),
        ),
    ]
