# Generated by Django 5.2.5 on 2026-01-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HABUI_APP', '0003_alter_recurso_tipo_recursoalimentos_consumoalimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.FloatField(help_text='Concentración de CO₂ en ppm')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'co2'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.FloatField()),
                ('corriente', models.FloatField()),
                ('potencia', models.FloatField()),
                ('factor_potencia', models.FloatField(blank=True, null=True)),
                ('frecuencia', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'energia'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Humedad relativa (%)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'humedad'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoOxigeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.FloatField(help_text='Concentración de O₂ en %')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'oxigeno'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en °C')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'temperatura'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Temperatura en °C')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(limit_choices_to={'tipo': 'temperatura_alimentos'}, on_delete=django.db.models.deletion.CASCADE, to='HABUI_APP.recurso')),
            ],
        ),
    ]
